// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class User_Receiving {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/main/resources/TestDriver/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void receiving() throws InterruptedException {
    driver.get("http://localhost:8090/");
    driver.manage().window().setSize(new Dimension(876, 681));
    Thread.sleep(500);
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    Thread.sleep(500);
    driver.findElement(By.cssSelector("input:nth-child(2)")).sendKeys("A1");
    Thread.sleep(500);
    driver.findElement(By.cssSelector("input:nth-child(1)")).sendKeys("A1");
    Thread.sleep(500);
    driver.findElement(By.cssSelector("button")).click();
    Thread.sleep(500);
    driver.findElement(By.linkText("用户信息")).click();
    Thread.sleep(500);
    driver.findElement(By.cssSelector(".el-menu-item-group:nth-child(3) .el-menu-item")).click();
    Thread.sleep(1000);
  }
}
