// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

public class Auto_off {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\Program Files\\Google\\Chrome\\Application\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void autooff() throws InterruptedException {
    driver.get("http://localhost:8090/");
    driver.manage().window().setSize(new Dimension(1721, 927));
    {
      WebElement dropdown = driver.findElement(By.cssSelector("select"));
      dropdown.findElement(By.xpath("//option[. = 'Admin']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    driver.findElement(By.cssSelector("input:nth-child(2)")).sendKeys("admin123");
    driver.findElement(By.cssSelector("input:nth-child(1)")).sendKeys("admin123");
    driver.findElement(By.cssSelector("button")).click();    Thread.sleep(500);
    {
      WebElement element = driver.findElement(By.cssSelector("button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    Thread.sleep(500);
    driver.findElement(By.xpath("//li[2]/div")).click();
    Thread.sleep(500);
    driver.findElement(By.xpath("//li[2]/ul/li/ul/li")).click();
    Thread.sleep(500);
    driver.findElement(By.xpath("//li/ul/li[2]")).click();
    Thread.sleep(500);
    driver.findElement(By.xpath("//li[4]/ul/li/ul/li[2]")).click();
    Thread.sleep(500);
    driver.findElement(By.xpath("//span[contains(.,\'完成\')]")).click();
    Thread.sleep(500);
    driver.findElement(By.xpath("//li/ul/li[2]")).click();
    Thread.sleep(500);
    driver.findElement(By.xpath("//li[3]")).click();
    Thread.sleep(500);
  }
}
