// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

public class Change_order_info {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\Program Files\\Google\\Chrome\\Application\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void changeorderinfo() throws InterruptedException {
    driver.get("http://localhost:8090/");
    driver.manage().window().setSize(new Dimension(876, 681));
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    driver.findElement(By.cssSelector("input:nth-child(2)")).sendKeys("A1");
    driver.findElement(By.cssSelector("input:nth-child(1)")).sendKeys("A1");
    driver.findElement(By.cssSelector("button")).click();Thread.sleep(500);
    {
      WebElement element = driver.findElement(By.cssSelector("button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("用户信息")).click();Thread.sleep(500);
    driver.findElement(By.cssSelector(".el-sub-menu__title")).click();Thread.sleep(500);
    driver.findElement(By.cssSelector(".el-menu--inline .el-menu-item:nth-child(1)")).click();Thread.sleep(500);
    driver.findElement(By.cssSelector(".el-table__row:nth-child(1) span")).click();Thread.sleep(500);
    {
      WebElement element = driver.findElement(By.cssSelector(".el-table__row:nth-child(1) span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }Thread.sleep(500);
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.xpath("//tr[10]/td[7]/div/div/div/div/div/form/div/div/div/div/input")).click();Thread.sleep(500);
    driver.findElement(By.xpath("//tr[10]/td[7]/div/div/div/div/div/form/div/div/div/div/input")).sendKeys("123");Thread.sleep(500);
    driver.findElement(By.xpath("//tr[10]/td[7]/div/div/div/div/div/form/div[2]/div/div/div/input")).click();Thread.sleep(500);
    driver.findElement(By.xpath("//tr[10]/td[7]/div/div/div/div/div/form/div[2]/div/div/div/input")).sendKeys("浙工商123");Thread.sleep(500);
    driver.findElement(By.xpath("//tr[10]/td[7]/div/div/div/div/footer/span/button/span")).click();Thread.sleep(1000);
  }
}
